kw_en = {
    "pa": "live",
    "ta": "die",
    "ka": "kind",
    "ba": "part",
    "da": "me",
    "ga": "you",
    "fa": "someone",
    "sa": "person",
    "ca": "thing",
    "la": "body",
    "ja": "word",
    "wa": "say",
    "ha": "true",
    "ma": "like",
    "pe": "good",
    "te": "bad",
    "ke": "big",
    "be": "small",
    "de": "none",
    "ge": "few",
    "fe": "some",
    "se": "many",
    "ce": "all",
    "le": "what",
    "je": "this",
    "we": "same",
    "he": "different",
    "me": "compared-to",
    "pi": "do",
    "ti": "happen",
    "ki": "go",
    "bi": "have",
    "di": "cause",
    "gi": "know",
    "fi": "think",
    "si": "feel",
    "ci": "want",
    "li": "reject",
    "ji": "touch",
    "wi": "see",
    "hi": "hear",
    "mi": "if",
    "pu": "not",
    "tu": "maybe",
    "ku": "can",
    "bu": "very",
    "du": "more",
    "gu": "time",
    "fu": "now",
    "su": "before",
    "cu": "after",
    "lu": "long time",
    "ju": "short time",
    "wu": "some time",
    "hu": "a moment",
    "mu": "because",
    "po": "0",
    "to": "1",
    "ko": "2",
    "bo": "3",
    "do": "4",
    "go": "place",
    "fo": "here",
    "so": "above",
    "co": "below",
    "lo": "far",
    "jo": "near",
    "wo": "side",
    "ho": "inside",
    "mo": "are",
    "pan": "head",
    "tan": "blood",
    "kan": "bone",
    "ban": "flesh",
    "dan": "metal",
    "gan": "glass",
    "fan": "cloth",
    "san": "colour",
    "can": "number",
    "lan": "shape",
    "jan": "text",
    "wan": "picture",
    "han": "take",
    "man": "give",
    "pen": "long",
    "ten": "wide",
    "ken": "tall",
    "ben": "round",
    "den": "soft",
    "gen": "sharp",
    "fen": "smooth",
    "sen": "heavy",
    "cen": "strong",
    "len": "new",
    "jen": "hot",
    "wen": "cold",
    "hen": "hole",
    "men": "surface",
    "pin": "sky",
    "tin": "moon",
    "kin": "sun",
    "bin": "ground",
    "din": "stars",
    "gin": "water",
    "fin": "fire",
    "sin": "wood",
    "cin": "stone",
    "lin": "house",
    "jin": "group",
    "win": "grain",
    "hin": "sweet",
    "min": "eat/drink",
    "pun": "creature",
    "tun": "plant",
    "kun": "breathe",
    "bun": "sleep",
    "dun": "health",
    "gun": "male",
    "fun": "female",
    "sun": "parent",
    "cun": "love",
    "lun": "start",
    "jun": "middle",
    "wun": "end",
    "hun": "tool",
    "mun": "trade",
    "pon": "5",
    "ton": "6",
    "kon": "7",
    "bon": "8",
    "don": "9",
    "gon": "try",
    "fon": "need",
    "son": "change",
    "con": "make",
    "lon": "break",
    "jon": "play",
    "won": "laugh",
    "hon": "learn",
    "mon": "sex",
    "na": "**ᴛ**",
    "ne": "**s**",
    "ni": "**ʟ**",
    "nu": "**ᴄ**",
    "no": "**ᴏ**",
    "nan": "ᴇᴍᴘʜ",
    "nen": "ᴄᴏɴғ",
    "nin": "ɪᴍᴘ",
    "nun": "ᴏ̨ɴ",
    "non": "ᴏ̨ᴜᴏ",
    "a": "**for**",
    "e": "**and**",
    "i": "**or**",
    "u": "**but**",
    "o": "**of**",
    "an": "**about**",
    "en": "**with**",
    "in": "**from**",
    "un": "**to**",
    "on": "**using**",
    ":": ":",
    "dfj": "i think this :",
    "!": "!",
    ",": ",",
    ".": ".",
}

kw_tr = {
    "pa": "`pa` : to live, to be alive/living; life;",
    "ta": "`ta` : to die, to be dead/dying; death;",
    "ka": "`ka` : a kind of X, a type of X;\n> **kawa** = *kind of saying* (language).\n> **sa ne kapun** = *a person is a kind of animal*.",
    "ba": "`ba` : a part of X;\n>**bala** = *part of body (body part)*",
    "da": "`da` : I, me, we, us, ours;",
    "ga": "`ga` : you, yours;",
    "fa": "`fa` : someone; they, them, theirs;",
    "sa": "`sa` : person (not necessarily human); a personality;",
    "ca": "`ca` : a thing, something; object, article, item;",
    "la": "`la` : body, figure, shape; the main part of X;",
    "ja": "`ja` : word, name;\n> **ja da** = *my name*",
    "wa": "`wa` : say, speak, utter, declare, state;",
    "ha": "`ha` : true, correct; yes;",
    "ma": "`ma` : like, as, similar to;\n> **da ne ma no ga** = *i am like you*",
    "pe": "`pe` : good, fine, OK, great; positive;\n> **kinpe** = *good sun (hello).*",
    "te": "`te` : bad, evil, harsh, toxic; negative",
    "ke": "`ke` : big, large, huge;",
    "be": "`be` : small, tiny, little (size);",
    "de": "`de` : zero, zilch;",
    "ge": "`ge` : few, little;",
    "fe": "`fe` : some, several;",
    "se": "`se` : many",
    "ce": "`ce` : all, every, each;",
    "le": "`le` : what, which, who, where;",
    "je": "`je` : this",
    "we": "`we` : same, similar; X is the same as/similar to Y;",
    "he": "`he` : different, other; X is different to Y;",
    "me": "`me` : compared to, comparison; compared to X;",
    "pi": "`pi` : to do; to achieve;",
    "ti": "`ti` : to happen; to take place;",
    "ki": "`ki` : to go; to come; to move;",
    "bi": "`bi` : to have, to posess; to hold;",
    "di": "`di` : to cause, to engender; a cause/reason;",
    "gi": "`gi` : to know; to be aware of; to understand;",
    "fi": "`fi` : to think; to reflect;",
    "si": "`fi` : to feel; to sense;",
    "ci": "`ci` : to want; to wish; should, must;",
    "li": "`li` : to reject, to refuse; to not want; to discard/throw away; trash;",
    "ji": "`ji` : to touch;",
    "wi": "`wi` : to see, to notice; sight;",
    "hi": "`hi` : to hear; to listen;",
    "mi": "`mi` : if, whether; a condition, an assumption; to suppose;",
    "pu": "`pu` : not; opposite; don't;",
    "tu": "`tu` : maybe, possibly; a chance, a possibility; a risk;",
    "ku": "`ku` : to be able to; can; an ability, a skill;",
    "bu": "`bu` : very; intensity;",
    "du": "`du` : more;",
    "gu": "time",
    "fu": "now",
    "su": "before",
    "cu": "after",
    "lu": "long time",
    "ju": "short time",
    "wu": "some time",
    "hu": "a moment",
    "mu": "because",
    "po": "0",
    "to": "1",
    "ko": "2",
    "bo": "3",
    "do": "4",
    "go": "place",
    "fo": "here",
    "so": "above",
    "co": "below",
    "lo": "far",
    "jo": "near",
    "wo": "side",
    "ho": "inside",
    "mo": "are",
    "pan": "head",
    "tan": "blood",
    "kan": "bone",
    "ban": "flesh",
    "dan": "metal",
    "gan": "glass",
    "fan": "cloth",
    "san": "colour",
    "can": "number",
    "lan": "shape",
    "jan": "text",
    "wan": "picture",
    "han": "take",
    "man": "give",
    "pen": "long",
    "ten": "wide",
    "ken": "tall",
    "ben": "round",
    "den": "soft",
    "gen": "sharp",
    "fen": "smooth",
    "sen": "heavy",
    "cen": "strong",
    "len": "now",
    "jen": "hot",
    "wen": "cold",
    "hen": "hole",
    "men": "surface",
    "pin": "sky",
    "tin": "moon",
    "kin": "sun",
    "bin": "ground",
    "din": "stars",
    "gin": "water",
    "fin": "fire",
    "sin": "wood",
    "cin": "stone",
    "lin": "house",
    "jin": "group",
    "win": "grain",
    "hin": "sweet",
    "min": "eat/drink",
    "pun": "creature",
    "tun": "plant",
    "kun": "breathe",
    "bun": "sleep",
    "dun": "health",
    "gun": "male",
    "fun": "female",
    "sun": "parent",
    "cun": "love",
    "lun": "start",
    "jun": "middle",
    "wun": "end",
    "hun": "tool",
    "mun": "trade",
    "pon": "5",
    "ton": "6",
    "kon": "7",
    "bon": "8",
    "don": "9",
    "gon": "try",
    "fon": "need",
    "son": "change",
    "con": "make",
    "lon": "break",
    "jon": "play",
    "won": "laugh",
    "hon": "learn",
    "mon": "sex",
    "na": "**ᴄ**",
    "ne": "**s**",
    "ni": "**ʟ**",
    "nu": "**ᴛ**",
    "no": "**ᴏ**",
    "nan": "ᴇᴍᴘʜ",
    "nen": "ᴄᴏɴғ",
    "nin": "ɪᴍᴘ",
    "nun": "ᴏ̨ɴ",
    "non": "ᴏ̨ᴜᴏ",
    "a": "**for**",
    "e": "**and**",
    "i": "**or**",
    "u": "**but**",
    "o": "**of**",
    "an": "**about**",
    "en": "**with**",
    "in": "**from**",
    "un": "**to**",
    "on": "**using**",
    ":": ":",
    "dfj": "i think this :",
    "!": "!",
    ",": ",",
    ".": ".",
}
