kw_en = {
    "pa": "live",
    "ta": "die",
    "ka": "kind",
    "ba": "part",
    "da": "me",
    "ga": "you",
    "fa": "someone",
    "sa": "person",
    "ca": "thing",
    "la": "body",
    "ja": "word",
    "wa": "say",
    "ha": "true",
    "ma": "like",
    "pe": "good",
    "te": "bad",
    "ke": "big",
    "be": "small",
    "de": "none",
    "ge": "few",
    "fe": "some",
    "se": "many",
    "ce": "all",
    "le": "what",
    "je": "this",
    "we": "same",
    "he": "different",
    "me": "compared-to",
    "pi": "do",
    "ti": "happen",
    "ki": "go",
    "bi": "have",
    "di": "cause",
    "gi": "know",
    "fi": "think",
    "si": "feel",
    "ci": "want",
    "li": "reject",
    "ji": "touch",
    "wi": "see",
    "hi": "hear",
    "mi": "if",
    "pu": "not",
    "tu": "maybe",
    "ku": "can",
    "bu": "very",
    "du": "more",
    "gu": "time",
    "fu": "now",
    "su": "before",
    "cu": "after",
    "lu": "long time",
    "ju": "short time",
    "wu": "some time",
    "hu": "a moment",
    "mu": "because",
    "po": "0",
    "to": "1",
    "ko": "2",
    "bo": "3",
    "do": "4",
    "go": "place",
    "fo": "here",
    "so": "above",
    "co": "below",
    "lo": "far",
    "jo": "near",
    "wo": "side",
    "ho": "inside",
    "mo": "are",
    "pan": "head",
    "tan": "blood",
    "kan": "bone",
    "ban": "flesh",
    "dan": "metal",
    "gan": "glass",
    "fan": "cloth",
    "san": "colour",
    "can": "number",
    "lan": "shape",
    "jan": "text",
    "wan": "picture",
    "han": "take",
    "man": "give",
    "pen": "long",
    "ten": "wide",
    "ken": "tall",
    "ben": "round",
    "den": "soft",
    "gen": "sharp",
    "fen": "smooth",
    "sen": "heavy",
    "cen": "strong",
    "len": "new",
    "jen": "hot",
    "wen": "cold",
    "hen": "hole",
    "men": "surface",
    "pin": "sky",
    "tin": "moon",
    "kin": "sun",
    "bin": "ground",
    "din": "stars",
    "gin": "water",
    "fin": "fire",
    "sin": "wood",
    "cin": "stone",
    "lin": "house",
    "jin": "group",
    "win": "grain",
    "hin": "sweet",
    "min": "eat/drink",
    "pun": "creature",
    "tun": "plant",
    "kun": "breathe",
    "bun": "sleep",
    "dun": "health",
    "gun": "male",
    "fun": "female",
    "sun": "parent",
    "cun": "love",
    "lun": "start",
    "jun": "middle",
    "wun": "end",
    "hun": "tool",
    "mun": "trade",
    "pon": "5",
    "ton": "6",
    "kon": "7",
    "bon": "8",
    "don": "9",
    "gon": "try",
    "fon": "need",
    "son": "change",
    "con": "make",
    "lon": "break",
    "jon": "play",
    "won": "laugh",
    "hon": "learn",
    "mon": "sex",
    "na": "**ᴛ**",
    "ne": "**s**",
    "ni": "**ʟ**",
    "nu": "**ᴄ**",
    "no": "**ᴏ**",
    "nan": "ᴇᴍᴘʜ",
    "nen": "ᴄᴏɴғ",
    "nin": "ɪᴍᴘ",
    "nun": "ᴏ̨ɴ",
    "non": "ᴏ̨ᴜᴏ",
    "a": "**for**",
    "e": "**and**",
    "i": "**or**",
    "u": "**but**",
    "o": "**of**",
    "an": "**about**",
    "en": "**with**",
    "in": "**from**",
    "un": "**to**",
    "on": "**using**",
    ":": ":",
    "dfj": "i think this :",
    "!": "!",
    ",": ",",
    ".": ".",
}

kw_tr = {
    "pa": "to live, to be alive/living; life",
    "ta": "to die, to be dead/dying; death",
    "ka": "a kind of X, a type of X\n> Example: kawa - kind of saying (language)\n> Example: a ne kapun - a person is a kind of animal.",
    "ba": "a part of X\n> Example: bala - *part of body (body part)*",
    "da": "I, me, we, us, ours",
    "ga": "you, yours",
    "fa": "someone; they, them, theirs",
    "sa": "person (not necessarily human); a personality",
    "ca": "a thing, something; object, article, item",
    "la": "body, figure, shape; the main part of X",
    "ja": "word, name\n> Example: ja da - my name",
    "wa": "say, speak, utter, declare, state",
    "ha": "true, correct; yes",
    "ma": "like, as, similar to\n> Example: da ne ma no ga - I am like you",
    "pe": "good, fine, OK, great; positive\n> Example: kinpe - good sun; hello",
    "te": "bad, evil, harsh, toxic; negative",
    "ke": "big, large, huge",
    "be": "small, tiny, little (size)",
    "de": "zero, zilch",
    "ge": "few, little",
    "fe": "some, several",
    "se": "many",
    "ce": "all, every, each",
    "le": "what, which, who, where",
    "je": "this",
    "we": "same, similar; X is the same as/similar to Y",
    "he": "different, other; X is different to Y",
    "me": "compared to, comparison; compared to X",
    "pi": "to do; to achieve",
    "ti": "to happen; to take place",
    "ki": "to go; to come; to move",
    "bi": "to have, to posess; to hold",
    "di": "to cause, to engender; a cause/reason",
    "gi": "to know; to be aware of; to understand",
    "fi": "to think; to reflect",
    "si": "to feel; to sense",
    "ci": "to want; to wish; should, must",
    "li": "to reject, to refuse; to not want; to discard/throw away; trash",
    "ji": "to touch",
    "wi": "to see, to notice; sight",
    "hi": "to hear; to listen",
    "mi": "if, whether; a condition, an assumption; to suppose",
    "pu": "not; opposite; don't",
    "tu": "maybe, possibly; a chance, a possibility; a risk",
    "ku": "to be able to; can; an ability, a skill",
    "bu": "very; intensity",
    "du": "more",
    "gu": "time",
    "fu": "now",
    "su": "before",
    "cu": "after",
    "lu": "long time",
    "ju": "short time",
    "wu": "some time",
    "hu": "a moment",
    "mu": "because",
    "po": "0",
    "to": "1",
    "ko": "2",
    "bo": "3",
    "do": "4",
    "go": "place",
    "fo": "here",
    "so": "above",
    "co": "below",
    "lo": "far",
    "jo": "near",
    "wo": "side",
    "ho": "inside",
    "mo": "are",
    "pan": "head",
    "tan": "blood",
    "kan": "bone",
    "ban": "flesh",
    "dan": "metal",
    "gan": "glass",
    "fan": "cloth",
    "san": "colour",
    "can": "number",
    "lan": "shape",
    "jan": "text",
    "wan": "picture",
    "han": "take",
    "man": "give",
    "pen": "long",
    "ten": "wide",
    "ken": "tall",
    "ben": "round",
    "den": "soft",
    "gen": "sharp",
    "fen": "smooth",
    "sen": "heavy",
    "cen": "strong",
    "len": "now",
    "jen": "hot",
    "wen": "cold",
    "hen": "hole",
    "men": "surface",
    "pin": "sky",
    "tin": "moon",
    "kin": "sun",
    "bin": "ground",
    "din": "stars",
    "gin": "water",
    "fin": "fire",
    "sin": "wood",
    "cin": "stone",
    "lin": "house",
    "jin": "group",
    "win": "grain",
    "hin": "sweet",
    "min": "eat/drink",
    "pun": "creature",
    "tun": "plant",
    "kun": "breathe",
    "bun": "sleep",
    "dun": "health",
    "gun": "male",
    "fun": "female",
    "sun": "parent",
    "cun": "love",
    "lun": "start",
    "jun": "middle",
    "wun": "end",
    "hun": "tool",
    "mun": "trade",
    "pon": "5",
    "ton": "6",
    "kon": "7",
    "bon": "8",
    "don": "9",
    "gon": "try",
    "fon": "need",
    "son": "change",
    "con": "make",
    "lon": "break",
    "jon": "play",
    "won": "laugh",
    "hon": "learn",
    "mon": "sex",
    "na": "(context particle)",
    "ne": "(subject particle)",
    "ni": "(location particle)",
    "nu": "(time particle)",
    "no": "(object particle)",
    "nan": "(emphasis particle)",
    "nen": "(confirmation particle)",
    "nin": "(imperative particle)",
    "nun": "(question particle)",
    "non": "(quotation particle)",
    "a": "for",
    "e": "and",
    "i": "or",
    "u": "but",
    "o": "of",
    "an": "about",
    "en": "with",
    "in": "from",
    "un": "to",
    "on": "using",
    ":": ":",
    "dfj": "i think this :",
    "!": "!",
    ",": ",",
    ".": ".",
}
